name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_URL: "http://localhost:4444"
    services:
      selenium-hub:
        image: selenium/hub:4.0.0-beta-3-prerelease-20210422
        ports:
          - 4442:4442
          - 4443:4443
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210422
        volumes:
          - /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        ports:
          - 6900:5900
      edge:
        image: selenium/node-edge:4.0.0-beta-3-prerelease-20210422
        volumes:
          - /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        ports:
          - 6901:5900
      firefox:
        image: selenium/node-firefox:4.0.0-beta-3-prerelease-20210422
        volumes:
          - /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        ports:
          - 6902:5900
      opera:
        image: selenium/node-opera:4.0.0-beta-3-prerelease-20210422
        volumes:
          - /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        ports:
          - 6903:5900
          
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test with Maven
      run: mvn -B test package --file pom.xml
